name: Create and Upload Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        default: 'v1.2'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      
    - name: Clone Repository
      run: |
        git clone https://user:${{ secrets.MURGI_PAT }}@github.com/mcpebd/mpack.git


    - name: Navigate to mpack and create zip
      run: |
        pushd mpack
        zip -r mpack.zip.mcpack . -x "*.git*" ".github/*" ".gitignore"
        popd

    - name: Create Release and Upload Artifact
      run: |
        gh release create ${{ github.event.inputs.release_tag }} mpack/mpack.zip.mcpack --title "${{ github.event.inputs.release_tag }}" --notes "A release" --latest
      env:
        GH_TOKEN: ${{ github.token }}


