name: Create and Upload Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        default: 'v1.0.0'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout temporary workspace
      run: mkdir workspace
      
    - name: Clone Repository
      run: |
        git clone https://user:${{ secrets.MURGI_PAT }}@github.com/mcpebd/mpack.git workspace/mpack


    - name: Navigate to mpack and create zip
      working-directory: workspace/mpack
      run: |
        zip -r mpack.zip.mcpack . -x "*.git*" ".github/*" ".gitignore"

    - name: Create Release and Upload Artifact
      run: |
        cd workspace/mpack
        gh release create ${{ github.event.inputs.release_tag }} mpack.zip.mcpack --title "Release ${{ github.event.inputs.release_tag }}" --notes "Automated release for tag ${{ github.event.inputs.release_tag }}" --latest
        env:
        GH_TOKEN: ${{ github.token }}


