name: Create Release and Upload Zip

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        required: true
        default: 'v1.0.0'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Clone the private repository (using a Personal Access Token)
      - name: Clone the private repo
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          git clone https://github.com/mcpebd/mpack.git

      # Step 3: Create a zip of the repository excluding specific files and directories
      - name: Zip the repository excluding .git, .github, .gitignore
        run: |
          # Navigate to the repo directory
          cd mpack

          # Create a zip of the root directory with exclusions
          zip -r ../mpack.zip.mcpack . -x "*.git*" -x ".github/*" -x ".gitignore"

      # Step 4: Create the release and upload the zip file
      - name: Create GitHub release and upload the zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create the release with the tag provided by the user
          TAG=${{ github.event.inputs.tag }}
          gh release create $TAG ../mpack.zip.mcpack --title "Release $TAG" --notes "Release notes for $TAG" --latest
