name: Create Release and Upload Zip

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        required: true
        default: 'v1.0.0'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Clone the private repository (using a Personal Access Token)
      - name: Clone the private repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This ensures authentication
        run: |
          git clone https://github.com/mcpebd/mpack.git

      # Step 3: Create a zip of the repository excluding specific files and directories
      - name: Zip the repository excluding .git, .github, .gitignore
        run: |
          cd mpack
          zip -r ../repo.zip . -x "*.git*" -x ".github/*" -x ".gitignore"

      # Step 4: Ensure the zip file is aligned to 4KB boundary
      - name: Align the zip file to 4KB
        run: |
          dd if=../repo.zip of=../repo-aligned.zip bs=4K seek=1 conv=notrunc

      # Step 5: Create the release and upload the zip
      - name: Create GitHub release and upload the zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ github.event.inputs.tag }}
          gh release create $TAG ../repo-aligned.zip --title "Release $TAG" --notes "Release notes for $TAG" --latest
